# Generated by Django 3.0.1 on 2021-02-20 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210219_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='documento',
            new_name='document',
        ),
    ]
