# Generated by Django 3.0.1 on 2021-02-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210223_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coeficient',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
