# Generated by Django 3.0.1 on 2021-02-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210224_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document',
            field=models.IntegerField(default=0),
        ),
    ]
