# Generated by Django 3.0.1 on 2021-03-08 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20210224_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='voter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='votantes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
