# Generated by Django 3.0.1 on 2021-03-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210308_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='voter',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='coeficient',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
