# Generated by Django 3.0.1 on 2021-03-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210308_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coeficient',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
    ]
