# Generated by Django 3.0.1 on 2021-02-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=127)),
                ('winning_option', models.CharField(max_length=127)),
                ('winning_coeficient', models.DecimalField(decimal_places=5, max_digits=5)),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fin', models.DateTimeField()),
            ],
        ),
    ]
