# Generated by Django 3.0.1 on 2021-02-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=127)),
                ('coeficient', models.DecimalField(decimal_places=5, max_digits=5)),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='horario_fin',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='horario_inicio',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='winning_coeficient',
        ),
        migrations.AlterField(
            model_name='poll',
            name='winning_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Option'),
        ),
    ]
