# Generated by Django 3.0.1 on 2021-02-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20210223_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='method',
            field=models.CharField(choices=[('MC', 'Mayoría Calificada'), ('MS', 'Mayoría Simple')], default='MC', max_length=2),
        ),
        migrations.AlterField(
            model_name='option',
            name='coeficient',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='poll',
            name='winning_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning', to='poll.Option'),
        ),
    ]
