# Generated by Django 3.0.1 on 2021-02-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20210224_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='parameter',
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=5),
        ),
    ]
