# Generated by Django 3.0.1 on 2021-02-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_poll_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='coeficient',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='option',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
