# Generated by Django 3.0.1 on 2021-02-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20210224_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='method',
            field=models.CharField(choices=[('MC', 'Mayoría Calificada'), ('MS', 'Mayoría Simple'), ('QU', 'Verificación del cuórum')], default='MC', max_length=2),
        ),
    ]
