# Generated by Django 3.0.1 on 2021-02-24 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20210224_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='total_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='coeficient',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_time', models.DateTimeField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='poll.Option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='poll.Poll')),
            ],
        ),
    ]
