# Generated by Django 3.0.1 on 2021-02-26 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_auto_20210226_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(null='', on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='poll.Voter'),
        ),
    ]
