# Generated by Django 3.0.1 on 2021-02-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_auto_20210226_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
    ]
