# Generated by Django 3.0.1 on 2021-02-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_auto_20210226_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voter',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='total_shares',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='voters',
        ),
    ]
