# Generated by Django 3.0.1 on 2021-02-26 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0018_auto_20210226_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='winning_option',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='poll.Poll'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='poll.Voter'),
        ),
    ]
