# Generated by Django 3.0.1 on 2021-02-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_auto_20210226_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='max_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='max_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='coeficient',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
    ]
