# Generated by Django 3.0.1 on 2021-03-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0021_auto_20210302_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='criteria',
            field=models.CharField(choices=[(1, 'Individual'), (2, 'Coeficient'), (3, 'Shares')], default=2, max_length=2),
        ),
        migrations.AlterField(
            model_name='poll',
            name='method',
            field=models.CharField(choices=[(1, 'Mayoria Calificada'), (2, 'Mayoria Simple'), (3, 'Verifica Quorum')], default=1, max_length=2),
        ),
    ]
