# Generated by Django 3.0.1 on 2021-03-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0022_auto_20210302_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='criteria',
            field=models.CharField(choices=[('IN', 'Individual'), ('CO', 'Coeficient'), ('SH', 'Shares')], default='CO', max_length=2),
        ),
        migrations.AlterField(
            model_name='poll',
            name='method',
            field=models.CharField(choices=[('MC', 'Mayoria Calificada'), ('MS', 'Mayoria Simple'), ('VQ', 'Verifica Quorum')], default='MC', max_length=2),
        ),
    ]
