# Generated by Django 3.0.1 on 2021-03-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0026_auto_20210305_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='criteria',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Coeficiente', 'Coeficient'), ('Acciones', 'Shares')], default='Coeficiente', max_length=11),
        ),
        migrations.AlterField(
            model_name='poll',
            name='method',
            field=models.CharField(choices=[('Mayoria Calificada', 'Mayoria Calificada'), ('Mayoría Simple', 'Mayoria Simple'), ('Verificación del Quorum', 'Verifica Quorum')], default='Mayoria Calificada', max_length=23),
        ),
    ]
