# Generated by Django 3.0.1 on 2021-03-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0028_auto_20210308_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='coeficient',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='poll',
            name='parameter',
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=2),
        ),
    ]
